// packages/react-conveyer/src/App.tsx
import React, { useRef } from 'react';
import './App.css';
import { useConveyer } from './react-conveyer/useConveyer';

function App() {
  const ref = useRef<HTMLElement>(null)  as any as ((e: HTMLElement | null) => void) & { current: HTMLElement | null };
  const {
    isReachStart,
    isReachEnd,
    scrollIntoView,
    onBeginScroll,
    onFinishScroll,
  } = useConveyer(ref, {
    preventClickOnDrag: true,
    horizontal: false,
  });

  onBeginScroll(() => {
    console.log("begin scroll");
  }, []);
  onFinishScroll(() => {
    console.log("finish scroll");
  }, []);

  return (
    <div className="App">
      <button id="prev" disabled={isReachStart} onClick={() => {
        // start to end
        scrollIntoView("start", {
          align: "end",
          duration: 500,
        });
      }}>PREV</button>
      <button id="next" disabled={isReachEnd} onClick={() => {
        // end to start
        scrollIntoView("end", {
          align: "start",
          duration: 500,
        });
      }}>NEXT</button>
      <div className="items" ref={ref}>
        <div className="item"><a href="#1">1</a></div>
        <div className="item"><a href="#2">2</a></div>
        <div className="item"><a href="#3">3</a></div>
        <div className="item"><a href="#4">4</a></div>
        <div className="item"><a href="#5">5</a></div>
        <div className="item"><a href="#6">6</a></div>
        <div className="item"><a href="#7">7</a></div>
        <div className="item"><a href="#8">8</a></div>
        <div className="item"><a href="#9">9</a></div>
        <div className="item"><a href="#10">10</a></div>
        <div className="item"><a href="#11">11</a></div>
        <div className="item"><a href="#12">12</a></div>
      </div>
    </div>
  );
}

export default App;

// packages/ngx-conveyer/src/app/app.component.ts
import { Component, ViewChild } from "@angular/core";
import { NgxInfiniteGridComponent } from "@egjs/ngx-infinitegrid";
import { OnRequestAppend, OnRenderComplete } from "@egjs/infinitegrid";
import { NgxConveyerDirective } from "projects/ngx-conveyer/src/public-api";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  @ViewChild("ig", { static: false }) ig!: NgxInfiniteGridComponent;
  @ViewChild("conveyer", { static: false }) conveyer!: NgxConveyerDirective;
  items = this.getItems(0, 10);
  getItems(nextGroupKey: number, count: number) {
    const nextItems = [];
    const nextKey = nextGroupKey * count;

    for (let i = 0; i < count; ++i) {
      nextItems.push({ groupKey: nextGroupKey, key: nextKey + i });
    }
    return nextItems;
  }
  groupBy(_: any, item: any) {
    return item.groupKey;
  }
  trackBy(_: any, item: any) {
    return item.key;
  }
  onRequestAppend(e: OnRequestAppend) {
    const nextGroupKey = (+e.groupKey! || 0) + 1;

    this.items = [...this.items, ...this.getItems(nextGroupKey, 10)];
  }
  onRenderComplete(e: OnRenderComplete) {
    this.conveyer.setItems(
      e.currentTarget.getItems().map((item) => ({
        element: item.element,
        pos: item.computedContentPos,
        size: item.contentSize,
      }))
    );
    this.conveyer.updateContainer();
  }
  prev() {
    this.conveyer.scrollIntoView("start", {
      align: "end",
      duration: 500,
    });
  }
  next() {
    this.conveyer.scrollIntoView("end", {
      align: "start",
      duration: 500,
    });
  }
  beginScroll(e: any) {
    (console as any).log("begin", e);
  }
  finishScroll(e: any) {
    (console as any).log("finish", e);
  }
}

<div class="examples">
  <div class="buttons">
    <button class="prev" [disabled]="conveyer?.isReachStart" (click)="prev()">
      prev
    </button>
    <button class="next" [disabled]="conveyer?.isReachEnd" (click)="next()">
      next
    </button>
  </div>
  <div
    NgxMasonryInfiniteGrid
    class="items"
    [gap]="5"
    [align]="'justify'"
    [items]="items"
    [trackBy]="trackBy"
    [groupBy]="groupBy"
    (requestAppend)="onRequestAppend($event)"
    (renderComplete)="onRenderComplete($event)"
    [horizontal]="false"
    [container]="true"
    [ngxConveyer]="{ horizontal: false }"
    (beginScroll)="beginScroll($event)"
    (finishScroll)="finishScroll($event)"
    (ab)="finishScroll($event)"
    #conveyer="ngxConveyer"
    #ig
  >
    <div class="item" *ngFor="let item of ig.visibleItems; trackBy: trackBy;">
      {{item.key}}
    </div>
  </div>
</div>
